cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED BUNDLE_DIR OR NOT IS_DIRECTORY "${BUNDLE_DIR}")
    message(FATAL_ERROR "BUNDLE_DIR must name an extracted tracy-embedded-native directory")
endif()
if(NOT EXISTS "${BUNDLE_DIR}/manifest.txt")
    message(FATAL_ERROR "Bundle is missing manifest.txt")
endif()

file(STRINGS "${BUNDLE_DIR}/manifest.txt" _manifest_lines ENCODING UTF-8)
set(_keys)
foreach(_line IN LISTS _manifest_lines)
    if(NOT _line MATCHES "^([A-Za-z0-9_.\/-]+)=(.*)$")
        message(FATAL_ERROR "Malformed manifest line: ${_line}")
    endif()
    set(_key "${CMAKE_MATCH_1}")
    set(_value "${CMAKE_MATCH_2}")
    if(_key IN_LIST _keys)
        message(FATAL_ERROR "Duplicate manifest key: ${_key}")
    endif()
    list(APPEND _keys "${_key}")
    string(MAKE_C_IDENTIFIER "${_key}" _identifier)
    set("_manifest_${_identifier}" "${_value}")
endforeach()

function(_require key expected)
    string(MAKE_C_IDENTIFIER "${key}" _identifier)
    if(NOT DEFINED "_manifest_${_identifier}")
        message(FATAL_ERROR "Manifest is missing ${key}")
    endif()
    if(NOT "${expected}" STREQUAL "" AND NOT "${_manifest_${_identifier}}" STREQUAL "${expected}")
        message(FATAL_ERROR
            "Manifest ${key} is '${_manifest_${_identifier}}', expected '${expected}'"
        )
    endif()
endfunction()

_require(bundle_format_version 1)
_require(tracy_extensions_version 0.5.0)
_require(tracy_version 0.13.1)
_require(tracy_protocol 76)
_require(target_triple "${EXPECTED_TARGET}")
_require(architecture "")
_require(platform "")
_require(build_profile release)
_require(native_feature_profile embedded-capture-v1)
_require(native_definitions "embedded_capture,enable,on_demand,manual_lifetime,delayed_init,timer_fallback,no_system_tracing,no_context_switch,no_sampling,no_code_transfer,no_broadcast,no_callstack_inlines,no_crash_handler,no_verify,no_debuginfod,no_demangle,no_fibers,no_flush_on_exit,no_only_localhost,no_only_ipv4,no_build_testing")
_require(pic_policy enabled)
_require(runtime_abi "")
_require(deployment_baseline "")
_require(compiler "")
if(DEFINED EXPECTED_COMMIT AND NOT EXPECTED_COMMIT STREQUAL "")
    _require(source_commit "${EXPECTED_COMMIT}")
else()
    _require(source_commit "")
endif()
_require(embedded_archive "")
_require(capstone_archive "")
_require(zstd_archive "")
_require(expected_files "")

foreach(_archive_key IN ITEMS embedded_archive capstone_archive zstd_archive)
    string(MAKE_C_IDENTIFIER "${_archive_key}" _identifier)
    set(_name "${_manifest_${_identifier}}")
    if(_name MATCHES "[/\\]" OR _name MATCHES "^\\.")
        message(FATAL_ERROR "Unsafe ${_archive_key}: ${_name}")
    endif()
    if(NOT EXISTS "${BUNDLE_DIR}/lib/${_name}")
        message(FATAL_ERROR "Manifest ${_archive_key} does not exist in lib/: ${_name}")
    endif()
endforeach()

set(_expected_files_csv "${_manifest_expected_files}")
string(REPLACE "," ";" _expected_files "${_expected_files_csv}")
list(SORT _expected_files)
set(_deduplicated "${_expected_files}")
list(REMOVE_DUPLICATES _deduplicated)
if(NOT _deduplicated STREQUAL _expected_files)
    message(FATAL_ERROR "Manifest expected_files contains duplicates")
endif()

file(GLOB_RECURSE _actual_entries RELATIVE "${BUNDLE_DIR}" LIST_DIRECTORIES false "${BUNDLE_DIR}/*")
list(SORT _actual_entries)
set(_expected_with_manifest manifest.txt ${_expected_files})
list(SORT _expected_with_manifest)
if(NOT _actual_entries STREQUAL _expected_with_manifest)
    message(FATAL_ERROR
        "Bundle inventory mismatch\nactual: ${_actual_entries}\nexpected: ${_expected_with_manifest}"
    )
endif()

foreach(_file IN LISTS _expected_files)
    set(_path "${BUNDLE_DIR}/${_file}")
    if(IS_SYMLINK "${_path}")
        message(FATAL_ERROR "Bundle payload must not be a symlink: ${_file}")
    endif()
    file(SIZE "${_path}" _size)
    if(_size EQUAL 0)
        message(FATAL_ERROR "Bundle payload is empty: ${_file}")
    endif()
    file(SHA256 "${_path}" _actual_sha)
    string(MAKE_C_IDENTIFIER "sha256.${_file}" _sha_identifier)
    if(NOT DEFINED "_manifest_${_sha_identifier}")
        message(FATAL_ERROR "Manifest has no checksum for ${_file}")
    endif()
    if(NOT _actual_sha STREQUAL "${_manifest_${_sha_identifier}}")
        message(FATAL_ERROR "SHA-256 mismatch for ${_file}")
    endif()
endforeach()

list(LENGTH _expected_files _payload_count)
math(EXPR _required_key_count "19 + ${_payload_count}")
list(LENGTH _keys _actual_key_count)
if(NOT _actual_key_count EQUAL _required_key_count)
    message(FATAL_ERROR
        "Manifest contains unexpected keys (${_actual_key_count}, expected ${_required_key_count})"
    )
endif()
message(STATUS "Verified embedded-native bundle for ${_manifest_target_triple}")
